package pl.san.jakub.tools;

/**
 * Created by Jakub on 19.12.2015.
 *
 * Error codes from Microsoft websites:
 * https://msdn.microsoft.com/en-us/library/windows/desktop/aa370674(v=vs.85).aspx
 * https://msdn.microsoft.com/en-us/library/windows/desktop/ms681385(v=vs.85).aspx
 *
 */
public enum NetApiError {

    EXIT_CODE_SUCCESS("The operation completed successfully.",0),
    EXIT_CODE_INCORECT_PARAMETER("The parameter is incorrect.", 87),
    EXIT_CODE_INCORECT_NETWORK_PASS("The specified network password is not correct.", 86),
    ERROR_PASSWORD_RESTRICTION("Unable to update the password. The value provided for the new password does not meet the length, complexity, or history requirements of the domain.",1325),
    ERROR_CANT_ACCESS_DOMAIN_INFO("Configuration information could not be read from the domain controller, either because the machine is unavailable, or access has been denied.", 1351),
    NERR_NetNotStarted("The workstation driver is not installed.",2102),
    NERR_UnknownServer("The server could not be located.",2103),
    NERR_ShareMem("An internal error occurred. The network cannot access a shared memory segment.",2104),
    NERR_NoNetworkResource("A network resource shortage occurred.",2105),
    NERR_RemoteOnly("This operation is not supported on workstations.",2106),
    NERR_DevNotRedirected("The device is not connected.",2107),
    NERR_ServerNotStarted("The Server service is not started.",2114),
    NERR_ItemNotFound("The queue is empty.",2115),
    NERR_UnknownDevDir("The device or directory does not exist.",2116),
    NERR_RedirectedPath("The operation is invalid on a redirected resource.",2117),
    NERR_DuplicateShare("The name has already been shared.",2118),
    NERR_NoRoom("The server is currently out of the requested resource.",2119),
    NERR_TooManyItems("Requested addition of items exceeds the maximum allowed.",2121),
    NERR_InvalidMaxUsers("The Peer service supports only two simultaneous users.",2122),
    NERR_BufTooSmall("The API return buffer is too small.",2123),
    NERR_RemoteErr("A remote API error occurred.",2127),
    NERR_LanmanIniError("An error occurred when opening or reading the configuration file.",2131),
    NERR_NetworkError("A general network error occurred.",2136),
    NERR_WkstaInconsistentState("The Workstation service is in an inconsistent state. Restart the computer before restarting the Workstation service.",2137),
    NERR_WkstaNotStarted("The Workstation service has not been started.",2138),
    NERR_BrowserNotStarted("The requested information is not available.",2139),
    NERR_InternalError("An internal error occurred.",2140),
    NERR_BadTransactConfig("The server is not configured for transactions.",2141),
    NERR_InvalidAPI("The requested API is not supported on the remote server.",2142),
    NERR_BadEventName("The event name is invalid.",2143),
    NERR_DupNameReboot("The computer name already exists on the network. Change it and restart the computer.",2144),
    NERR_CfgCompNotFound("The specified component could not be found in the configuration information.",2146),
    NERR_CfgParamNotFound("The specified parameter could not be found in the configuration information.",2147),
    NERR_LineTooLong("A line in the configuration file is too long.",2149),
    NERR_QNotFound("The printer does not exist.",2150),
    NERR_JobNotFound("The print job does not exist.",2151),
    NERR_DestNotFound("The printer destination cannot be found.",2152),
    NERR_DestExists("The printer destination already exists.",2153),
    NERR_QExists("The printer queue already exists.",2154),
    NERR_QNoRoom("No more printers can be added.",2155),
    NERR_JobNoRoom("No more print jobs can be added.",2156),
    NERR_DestNoRoom("No more printer destinations can be added.",2157),
    NERR_DestIdle("This printer destination is idle and cannot accept control operations.",2158),
    NERR_DestInvalidOp("This printer destination request contains an invalid control function.",2159),
    NERR_ProcNoRespond("The print processor is not responding.",2160),
    NERR_SpoolerNotLoaded("The spooler is not running.",2161),
    NERR_DestInvalidState("This operation cannot be performed on the print destination in its current state.",2162),
    NERR_QinvalidState("This operation cannot be performed on the printer queue in its current state.",2163),
    NERR_JobInvalidState("This operation cannot be performed on the print job in its current state.",2164),
    NERR_SpoolNoMemory("A spooler memory allocation failure occurred.",2165),
    NERR_DriverNotFound("The device driver does not exist.",2166),
    NERR_DataTypeInvalid("The data type is not supported by the print processor.",2167),
    NERR_ProcNotFound("The print processor is not installed.",2168),
    NERR_ServiceTableLocked("The service database is locked.",2180),
    NERR_ServiceTableFull("The service table is full.",2181),
    NERR_ServiceInstalled("The requested service has already been started.",2182),
    NERR_ServiceEntryLocked("The service does not respond to control actions.",2183),
    NERR_ServiceNotInstalled("The service has not been started.",2184),
    NERR_BadServiceName("The service name is invalid.",2185),
    NERR_ServiceCtlTimeout("The service is not responding to the control function.",2186),
    NERR_ServiceCtlBusy("The service control is busy.",2187),
    NERR_BadServiceProgName("The configuration file contains an invalid service program name.",2188),
    NERR_ServiceNotCtrl("The service could not be controlled in its present state.",2189),
    NERR_ServiceKillProc("The service ended abnormally.",2190),
    NERR_ServiceCtlNotValid("The requested pause or stop is not valid for this service.",2191),
    NERR_NotInDispatchTbl("The service control dispatcher could not find the service name in the dispatch table.",2192),
    NERR_BadControlRecv("The service control dispatcher pipe read failed.",2193),
    NERR_ServiceNotStarting("A thread for the new service could not be created.",2194),
    NERR_AlreadyLoggedOn("This workstation is already logged on to the local-area network.",2200),
    NERR_NotLoggedOn("The workstation is not logged on to the local-area network.",2201),
    NERR_BadUsername("The user name or group name parameter is invalid.",2202),
    NERR_BadPassword("The password parameter is invalid.",2203),
    NERR_UnableToAddName_W("@W The logon processor did not add the message alias.",2204),
    NERR_UnableToAddName_F("The logon processor did not add the message alias.",2205),
    NERR_UnableToDelName_W("@W The logoff processor did not delete the message alias.",2206),
    NERR_UnableToDelName_F("The logoff processor did not delete the message alias.",2207),
    NERR_LogonsPaused("Network logons are paused.",2209),
    NERR_LogonServerConflict("A centralized logon-server conflict occurred.",2210),
    NERR_LogonNoUserPath("The server is configured without a valid user path.",2211),
    NERR_LogonScriptError("An error occurred while loading or running the logon script.",2212),
    NERR_StandaloneLogon("The logon server was not specified. Your computer will be logged on as STANDALONE.",2214),
    NERR_LogonServerNotFound("The logon server could not be found.",2215),
    NERR_LogonDomainExists("There is already a logon domain for this computer.",2216),
    NERR_NonValidatedLogon("The logon server could not validate the logon.",2217),
    NERR_ACFNotFound("The security database could not be found.",2219),
    NERR_GroupNotFound("The group name could not be found.",2220),
    NERR_UserNotFound("The user name could not be found.",2221),
    NERR_ResourceNotFound("The resource name could not be found.",2222),
    NERR_GroupExists("The group already exists.",2223),
    NERR_UserExists("The user account already exists.",2224),
    NERR_ResourceExists("The resource permission list already exists.",2225),
    NERR_NotPrimary("This operation is only allowed on the primary domain controller of the domain.",2226),
    NERR_ACFNotLoaded("The security database has not been started.",2227),
    NERR_ACFNoRoom("There are too many names in the user accounts database.",2228),
    NERR_ACFFileIOFail("A disk I/O failure occurred.",2229),
    NERR_ACFTooManyLists("The limit of 64 entries per resource was exceeded.",2230),
    NERR_UserLogon("Deleting a user with a session is not allowed.",2231),
    NERR_ACFNoParent("The parent directory could not be located.",2232),
    NERR_CanNotGrowSegment("Unable to add to the security database session cache segment.",2233),
    NERR_SpeGroupOp("This operation is not allowed on this special group.",2234),
    NERR_NotInCache("This user is not cached in user accounts database session cache.",2235),
    NERR_UserInGroup("The user already belongs to this group.",2236),
    NERR_UserNotInGroup("The user does not belong to this group.",2237),
    NERR_AccountUndefined("This user account is undefined.",2238),
    NERR_AccountExpired("This user account has expired.",2239),
    NERR_InvalidWorkstation("The user is not allowed to log on from this workstation.",2240),
    NERR_InvalidLogonHours("The user is not allowed to log on at this time.",2241),
    NERR_PasswordExpired("The password of this user has expired.",2242),
    NERR_PasswordCantChange("The password of this user cannot change.",2243),
    NERR_PasswordHistConflict("This password cannot be used now.",2244),
    NERR_PasswordTooShort("The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements.",2245),
    NERR_PasswordTooRecent("The password of this user is too recent to change.",2246),
    NERR_InvalidDatabase("The security database is corrupted.",2247),
    NERR_DatabaseUpToDate("No updates are necessary to this replicant network/local security database.",2248),
    NERR_SyncRequired("This replicant database is outdated; synchronization is required.",2249),
    NERR_UseNotFound("The network connection could not be found.",2250),
    NERR_BadAsgType("This asg_type is invalid.",2251),
    NERR_DeviceIsShared("This device is currently being shared.",2252),
    NERR_NoComputerName("The computer name could not be added as a message alias. The name may already exist on the network.",2270),
    NERR_MsgAlreadyStarted("The Messenger service is already started.",2271),
    NERR_MsgInitFailed("The Messenger service failed to start.",2272),
    NERR_NameNotFound("The message alias could not be found on the network.",2273),
    NERR_AlreadyForwarded("This message alias has already been forwarded.",2274),
    NERR_AddForwarded("This message alias has been added but is still forwarded.",2275),
    NERR_AlreadyExists("This message alias already exists locally.",2276),
    NERR_TooManyNames("The maximum number of added message aliases has been exceeded.",2277),
    NERR_DelComputerName("The computer name could not be deleted.",2278),
    NERR_LocalForward("Messages cannot be forwarded back to the same workstation.",2279),
    NERR_GrpMsgProcessor("An error occurred in the domain message processor.",2280),
    NERR_PausedRemote("The message was sent, but the recipient has paused the Messenger service.",2281),
    NERR_BadReceive("The message was sent but not received.",2282),
    NERR_NameInUse("The message alias is currently in use. Try again later.",2283),
    NERR_MsgNotStarted("The Messenger service has not been started.",2284),
    NERR_NotLocalName("The name is not on the local computer.",2285),
    NERR_NoForwardName("The forwarded message alias could not be found on the network.",2286),
    NERR_RemoteFull("The message alias table on the remote station is full.",2287),
    NERR_NameNotForwarded("Messages for this alias are not currently being forwarded.",2288),
    NERR_TruncatedBroadcast("The broadcast message was truncated.",2289),
    NERR_InvalidDevice("This is an invalid device name.",2294),
    NERR_WriteFault("A write fault occurred.",2295),
    NERR_DuplicateName("A duplicate message alias exists on the network.",2297),
    NERR_DeleteLater("@W This message alias will be deleted later.",2298),
    NERR_IncompleteDel("The message alias was not successfully deleted from all networks.",2299),
    NERR_MultipleNets("This operation is not supported on computers with multiple networks.",2300),
    NERR_NetNameNotFound("This shared resource does not exist.",2310),
    NERR_DeviceNotShared("This device is not shared.",2311),
    NERR_ClientNameNotFound("A session does not exist with that computer name.",2312),
    NERR_FileIdNotFound("There is not an open file with that identification number.",2314),
    NERR_ExecFailure("A failure occurred when executing a remote administration command.",2315),
    NERR_TmpFile("A failure occurred when opening a remote temporary file.",2316),
    NERR_TooMuchData("The data returned from a remote administration command has been truncated to 64K.",2317),
    NERR_DeviceShareConflict("This device cannot be shared as both a spooled and a non-spooled resource.",2318),
    NERR_BrowserTableIncomplete("The information in the list of servers may be incorrect.",2319),
    NERR_NotLocalDomain("The computer is not active in this domain.",2320),
    NERR_IsDfsShare("The share must be removed from the Distributed File System before it can be deleted.",2321),
    NERR_DevInvalidOpCode("The operation is invalid for this device.",2331),
    NERR_DevNotFound("This device cannot be shared.",2332),
    NERR_DevNotOpen("This device was not open.",2333),
    NERR_BadQueueDevString("This device name list is invalid.",2334),
    NERR_BadQueuePriority("The queue priority is invalid.",2335),
    NERR_NoCommDevs("There are no shared communication devices.",2337),
    NERR_QueueNotFound("The queue you specified does not exist.",2338),
    NERR_BadDevString("This list of devices is invalid.",2340),
    NERR_BadDev("The requested device is invalid.",2341),
    NERR_InUseBySpooler("This device is already in use by the spooler.",2342),
    NERR_CommDevInUse("This device is already in use as a communication device.",2343),
    NERR_InvalidComputer("This computer name is invalid.",2351),
    NERR_MaxLenExceeded("The string and prefix specified are too long.",2354),
    NERR_BadComponent("This path component is invalid.",2356),
    NERR_CantType("Could not determine the type of input.",2357),
    NERR_TooManyEntries("The buffer for types is not big enough.",2362),
    NERR_ProfileFileTooBig("Profile files cannot exceed 64K.",2370),
    NERR_ProfileOffset("The start offset is out of range.",2371),
    NERR_ProfileCleanup("The system cannot delete current connections to network resources.",2372),
    NERR_ProfileUnknownCmd("The system was unable to parse the command line in this file.",2373),
    NERR_ProfileLoadErr("An error occurred while loading the profile file.",2374),
    NERR_ProfileSaveErr("@W Errors occurred while saving the profile file. The profile was partially saved.",2375),
    NERR_LogOverflow("Log file %1 is full.",2377),
    NERR_LogFileChanged("This log file has changed between reads.",2378),
    NERR_LogFileCorrupt("Log file %1 is corrupt.",2379),
    NERR_SourceIsDir("The source path cannot be a directory.",2380),
    NERR_BadSource("The source path is illegal.",2381),
    NERR_BadDest("The destination path is illegal.",2382),
    NERR_DifferentServers("The source and destination paths are on different servers.",2383),
    NERR_RunSrvPaused("The Run server you requested is paused.",2385),
    NERR_ErrCommRunSrv("An error occurred when communicating with a Run server.",2389),
    NERR_ErrorExecingGhost("An error occurred when starting a background process.",2391),
    NERR_ShareNotFound("The shared resource you are connected to could not be found.",2392),
    NERR_InvalidLana("The LAN adapter number is invalid.",2400),
    NERR_OpenFiles("There are open files on the connection.",2401),
    NERR_ActiveConns("Active connections still exist.",2402),
    NERR_BadPasswordCore("This share name or password is invalid.",2403),
    NERR_DevInUse("The device is being accessed by an active process.",2404),
    NERR_LocalDrive("The drive letter is in use locally.",2405),
    NERR_AlertExists("The specified client is already registered for the specified event.",2430),
    NERR_TooManyAlerts("The alert table is full.",2431),
    NERR_NoSuchAlert("An invalid or nonexistent alert name was raised.",2432),
    NERR_BadRecipient("The alert recipient is invalid.",2433),
    NERR_AcctLimitExceeded("A user's session with this server has been deleted",2434),
    NERR_InvalidLogSeek("The log file does not contain the requested record number.",2440),
    NERR_BadUasConfig("The user accounts database is not configured correctly.",2450),
    NERR_InvalidUASOp("This operation is not permitted when the Netlogon service is running.",2451),
    NERR_LastAdmin("This operation is not allowed on the last administrative account.",2452),
    NERR_DCNotFound("Could not find domain controller for this domain.",2453),
    NERR_LogonTrackingError("Could not set logon information for this user.",2454),
    NERR_NetlogonNotStarted("The Netlogon service has not been started.",2455),
    NERR_CanNotGrowUASFile("Unable to add to the user accounts database.",2456),
    NERR_TimeDiffAtDC("This server's clock is not synchronized with the primary domain controller's clock.",2457),
    NERR_PasswordMismatch("A password mismatch has been detected.",2458),
    NERR_NoSuchServer("The server identification does not specify a valid server.",2460),
    NERR_NoSuchSession("The session identification does not specify a valid session.",2461),
    NERR_NoSuchConnection("The connection identification does not specify a valid connection.",2462),
    NERR_TooManyServers("There is no space for another entry in the table of available servers.",2463),
    NERR_TooManySessions("The server has reached the maximum number of sessions it supports.",2464),
    NERR_TooManyConnections("The server has reached the maximum number of connections it supports.",2465),
    NERR_TooManyFiles("The server cannot open more files because it has reached its maximum number.",2466),
    NERR_NoAlternateServers("There are no alternate servers registered on this server.",2467),
    NERR_TryDownLevel("Try down-level (remote admin protocol) version of API instead.",2470),
    NERR_UPSDriverNotStarted("The UPS driver could not be accessed by the UPS service.",2480),
    NERR_UPSInvalidConfig("The UPS service is not configured correctly.",2481),
    NERR_UPSInvalidCommPort("The UPS service could not access the specified Comm Port.",2482),
    NERR_UPSSignalAsserted("The UPS indicated a line fail or low battery situation. Service not started.",2483),
    NERR_UPSShutdownFailed("The UPS service failed to perform a system shut down.",2484),
    NERR_BadDosRetCode("The program below returned an MS-DOS error code:",2500),
    NERR_ProgNeedsExtraMem("The program below needs more memory:",2501),
    NERR_BadDosFunction("The program below called an unsupported MS-DOS function:",2502),
    NERR_RemoteBootFailed("The workstation failed to boot.",2503),
    NERR_BadFileCheckSum("The file below is corrupt.",2504),
    NERR_NoRplBootSystem("No loader is specified in the boot-block definition file.",2505),
    NERR_RplLoadrNetBiosErr("NetBIOS returned an error: The NCB and SMB are dumped above.",2506),
    NERR_RplLoadrDiskErr("A disk I/O error occurred.",2507),
    NERR_ImageParamErr("Image parameter substitution failed.",2508),
    NERR_TooManyImageParams("Too many image parameters cross disk sector boundaries.",2509),
    NERR_NonDosFloppyUsed("The image was not generated from an MS-DOS diskette formatted with /S.",2510),
    NERR_RplBootRestart("Remote boot will be restarted later.",2511),
    NERR_RplSrvrCallFailed("The call to the Remoteboot server failed.",2512),
    NERR_CantConnectRplSrvr("Cannot connect to the Remoteboot server.",2513),
    NERR_CantOpenImageFile("Cannot open image file on the Remoteboot server.",2514),
    NERR_CallingRplSrvr("Connecting to the Remoteboot server...",2515),
    NERR_StartingRplBoot("Connecting to the Remoteboot server...",2516),
    NERR_RplBootServiceTerm("Remote boot service was stopped; check the error log for the cause of the problem.",2517),
    NERR_RplBootStartFailed("Remote boot startup failed; check the error log for the cause of the problem.",2518),
    NERR_RPL_CONNECTED("A second connection to a Remoteboot resource is not allowed.",2519),
    NERR_BrowserConfiguredToNotRun("The browser service was configured with MaintainServerList=No.",2550),
    NERR_RplNoAdaptersStarted("Service failed to start since none of the network adapters started with this service.",2610),
    NERR_RplBadRegistry("Service failed to start due to bad startup information in the registry.",2611),
    NERR_RplBadDatabase("Service failed to start because its database is absent or corrupt.",2612),
    NERR_RplRplfilesShare("Service failed to start because RPLFILES share is absent.",2613),
    NERR_RplNotRplServer("Service failed to start because RPLUSER group is absent.",2614),
    NERR_RplCannotEnum("Cannot enumerate service records.",2615),
    NERR_RplWkstaInfoCorrupted("Workstation record information has been corrupted.",2616),
    NERR_RplWkstaNotFound("Workstation record was not found.",2617),
    NERR_RplWkstaNameUnavailable("Workstation name is in use by some other workstation.",2618),
    NERR_RplProfileInfoCorrupted("Profile record information has been corrupted.",2619),
    NERR_RplProfileNotFound("Profile record was not found.",2620),
    NERR_RplProfileNameUnavailable("Profile name is in use by some other profile.",2621),
    NERR_RplProfileNotEmpty("There are workstations using this profile.",2622),
    NERR_RplConfigInfoCorrupted("Configuration record information has been corrupted.",2623),
    NERR_RplConfigNotFound("Configuration record was not found.",2624),
    NERR_RplAdapterInfoCorrupted("Adapter ID record information has been corrupted.",2625),
    NERR_RplInternal("An internal service error has occurred.",2626),
    NERR_RplVendorInfoCorrupted("Vendor ID record information has been corrupted.",2627),
    NERR_RplBootInfoCorrupted("Boot block record information has been corrupted.",2628),
    NERR_RplWkstaNeedsUserAcct("The user account for this workstation record is missing.",2629),
    NERR_RplNeedsRPLUSERAcct("The RPLUSER local group could not be found.",2630),
    NERR_RplBootNotFound("Boot block record was not found.",2631),
    NERR_RplIncompatibleProfile("Chosen profile is incompatible with this workstation.",2632),
    NERR_RplAdapterNameUnavailable("Chosen network adapter ID is in use by some other workstation.",2633),
    NERR_RplConfigNotEmpty("There are profiles using this configuration.",2634),
    NERR_RplBootInUse("There are workstations, profiles, or configurations using this boot block.",2635),
    NERR_RplBackupDatabase("Service failed to backup Remoteboot database.",2636),
    NERR_RplAdapterNotFound("Adapter record was not found.",2637),
    NERR_RplVendorNotFound("Vendor record was not found.",2638),
    NERR_RplVendorNameUnavailable("Vendor name is in use by some other vendor record.",2639),
    NERR_RplBootNameUnavailable("(boot name, vendor ID) is in use by some other boot block record.",2640),
    NERR_RplConfigNameUnavailable("Configuration name is in use by some other configuration.",2641),
    NERR_DfsInternalCorruption("The internal database maintained by the Dfs service is corrupt.",2660),
    NERR_DfsVolumeDataCorrupt("One of the records in the internal Dfs database is corrupt.",2661),
    NERR_DfsNoSuchVolume("There is no DFS name whose entry path matches the input Entry Path.",2662),
    NERR_DfsVolumeAlreadyExists("A root or link with the given name already exists.",2663),
    NERR_DfsAlreadyShared("The server share specified is already shared in the Dfs.",2664),
    NERR_DfsNoSuchShare("The indicated server share does not support the indicated DFS namespace.",2665),
    NERR_DfsNotALeafVolume("The operation is not valid on this portion of the namespace.",2666),
    NERR_DfsLeafVolume("The operation is not valid on this portion of the namespace.",2667),
    NERR_DfsVolumeHasMultipleServers("The operation is ambiguous because the link has multiple servers.",2668),
    NERR_DfsCantCreateJunctionPoint("Unable to create a link.",2669),
    NERR_DfsServerNotDfsAware("The server is not Dfs Aware.",2670),
    NERR_DfsBadRenamePath("The specified rename target path is invalid.",2671),
    NERR_DfsVolumeIsOffline("The specified DFS link is offline.",2672),
    NERR_DfsNoSuchServer("The specified server is not a server for this link.",2673),
    NERR_DfsCyclicalName("A cycle in the Dfs name was detected.",2674),
    NERR_DfsNotSupportedInServerDfs("The operation is not supported on a server-based Dfs.",2675),
    NERR_DfsDuplicateService("This link is already supported by the specified server-share.",2676),
    NERR_DfsCantRemoveLastServerShare("Can't remove the last server-share supporting this root or link.",2677),
    NERR_DfsVolumeIsInterDfs("The operation is not supported for an Inter-DFS link.",2678),
    NERR_DfsInconsistent("The internal state of the Dfs Service has become inconsistent.",2679),
    NERR_DfsServerUpgraded("The Dfs Service has been installed on the specified server.",2680),
    NERR_DfsDataIsIdentical("The Dfs data being reconciled is identical.",2681),
    NERR_DfsCantRemoveDfsRoot("The DFS root cannot be deleted. Uninstall DFS if required.",2682),
    NERR_DfsChildOrParentInDfs("A child or parent directory of the share is already in a Dfs.",2683),
    NERR_DfsInternalError("Dfs internal error.",2690),
    NERR_SetupAlreadyJoined("This computer is already joined to a domain.",2691),
    NERR_SetupNotJoined("This computer is not currently joined to a domain.",2692),
    NERR_SetupDomainController("This computer is a domain controller and cannot be unjoined from a domain.",2693),
    NERR_DefaultJoinRequired("The destination domain controller does not support creating machine accounts in OUs.",2694),
    NERR_InvalidWorkgroupName("The specified workgroup name is invalid.",2695),
    NERR_NameUsesIncompatibleCodePage("The specified computer name is incompatible with the default language used on the domain controller.",2696),
    NERR_ComputerAccountNotFound("The specified computer account could not be found.",2697),
    NERR_PersonalSku("This version of Windows cannot be joined to a domain.",2698),
    NERR_PasswordMustChange("The password must change at the next logon.",2701),
    NERR_AccountLockedOut("The account is locked out.",2702),
    NERR_PasswordTooLong("The password is too long.",2703),
    NERR_PasswordNotComplexEnough("The password does not meet the complexity policy.",2704),
    NERR_PasswordFilterError("The password does not meet the requirements of the password filter DLLs.",2705),
    NERR_NoOfflineJoinInfo("The offline join completion information was not found.",2709),
    NERR_BadOfflineJoinInfo("The offline join completion information was bad.",2710),
    NERR_CantCreateJoinInfo("Unable to create offline join information. Please ensure you have access to the specified path location and permissions to modify its contents. Running as an elevated administrator may be required.",2711),
    NERR_BadDomainJoinInfo("The domain join info being saved was incomplete or bad.",2712),
    NERR_JoinPerformedMustRestart("Offline join operation successfully completed but a restart is needed.",2713),
    NERR_NoJoinPending("There was no offline join operation pending.",2714),
    NERR_ValuesNotSet("Unable to set one or more requested machine or domain name values on the local computer.",2715),
    NERR_CantVerifyHostname("Could not verify the current machine's hostname against the saved value in the join completion information.",2716),
    NERR_CantLoadOfflineHive("Unable to load the specified offline registry hive. Please ensure you have access to the specified path location and permissions to modify its contents. Running as an elevated administrator may be required.",2717),
    NERR_ConnectionInsecure("The minimum session security requirements for this operation were not met.",2718),
    NERR_ProvisioningBlobUnsupported("Computer account provisioning blob version is not supported.",2719),
    ERROR_CODE_NOT_FOUND("Error code not found", 404);
    
    private String value;
    private int code;

    /**
     *
     * @param value Error code description
     * @param code Decimal error code
     */
    NetApiError(String value, int code) {
        this.value = value;
        this.code = code;
    }

    public String getValue() {
        return value;
    }

    public int getCode() {
        return code;
    }

    /**
     *
     * @param code WebApi32 or System Error code
     * @return If error code is not found returns default 404 - not found error.
     */
    public static NetApiError checkErrorCode(int code) {
        for (NetApiError netApiError : values()) {
            if(netApiError.getCode() == code) {
                return netApiError;
            }
        }
        return ERROR_CODE_NOT_FOUND;
    }
}
